grupo5imobiliario/urls.py
from django.contrib import admin
from django.urls import include, path
from radarimovel import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('radarimovel/', include('radarimovel.urls')),
    path('', views.index, name='index'),
]

radarimovel/urls.py
from django.urls import path
from . import views


app_name = 'radarimovel'
urlpatterns = [
  path('', views.index, name='index'),
  path('login',views.user_login,  name='login'),
  path('consulta', views.imoveis, name='consulta'),
  # path('consulta', views.proprietarios, name='consulta'),
  path('inserir', views.inserir, name='inserir'),
  path('logout/', views.user_logout, name='logout'),]

radarimovel/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Agencias(models.Model):
    id_agencia = models.AutoField(db_column='ID_agencia', primary_key=True)  # Field name made lowercase.
    id_rede = models.ForeignKey('RedeAgencia', models.DO_NOTHING, db_column='ID_rede', blank=True, null=True)  # Field name made lowercase.
    id_localizacao = models.ForeignKey('Localizacao', models.DO_NOTHING, db_column='ID_localizacao', blank=True, null=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=100, blank=True, null=True)  # Field name made lowercase.
    morada = models.CharField(db_column='Morada', max_length=100, blank=True, null=True)  # Field name made lowercase.
    licenca_ami = models.IntegerField(db_column='Licenca_AMI')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'agencias'

    def __str__(self):
        return self.nome


class Angaria(models.Model):
    nifconsultor = models.OneToOneField('Consultores', models.DO_NOTHING, db_column='nifconsultor', primary_key=True)  # The composite primary key (nifconsultor, id_imovel) found, that is not supported. The first column is selected.
    id_imovel = models.ForeignKey('Imovel', models.DO_NOTHING, db_column='id_imovel')
    data_entrada = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'angaria'
        unique_together = (('nifconsultor', 'id_imovel'),)


class Consultores(models.Model):
    nifconsultor = models.CharField(db_column='nifConsultor', primary_key=True, max_length=11)  # Field name made lowercase.
    idagencia = models.ForeignKey(Agencias, models.DO_NOTHING, db_column='IdAgencia', blank=True, null=True)  # Field name made lowercase.
    nome = models.CharField(max_length=255, blank=True, null=True)
    telefone = models.IntegerField(blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    landingpage = models.CharField(db_column='landingPage', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'consultores'

    def __str__(self):
        return self.nome


class Imovel(models.Model):
    id_imovel = models.AutoField(db_column='ID_Imovel', primary_key=True)  # Field name made lowercase.
    nifproprietario = models.ForeignKey('Proprietario', models.DO_NOTHING, db_column='NIFProprietario')  # Field name made lowercase.
    idlocalizacao = models.ForeignKey('Localizacao', models.DO_NOTHING, db_column='IDLocalizacao', blank=True, null=True)  # Field name made lowercase.
    tipo_de_imovel = models.CharField(db_column='Tipo_de_imovel', max_length=255)  # Field name made lowercase.
    tipologia = models.CharField(db_column='Tipologia', max_length=255)  # Field name made lowercase.
    morada = models.CharField(db_column='Morada', max_length=255)  # Field name made lowercase.
    codigo_postal = models.CharField(db_column='Codigo_postal', max_length=255)  # Field name made lowercase.
    preco_pedido = models.DecimalField(db_column='Preco_pedido', max_digits=12, decimal_places=0)  # Field name made lowercase.
    fotos = models.TextField(db_column='Fotos', blank=True, null=True)  # Field name made lowercase.
    area_m2 = models.IntegerField(blank=True, null=True)
    garagem_estacionamento = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'imovel'


class Localizacao(models.Model):
    id_localizacao = models.AutoField(db_column='ID_Localizacao', primary_key=True)  # Field name made lowercase.
    zona = models.CharField(db_column='Zona', max_length=255)  # Field name made lowercase.
    distrito = models.CharField(db_column='Distrito', max_length=255)  # Field name made lowercase.
    concelho = models.CharField(db_column='Concelho', max_length=255)  # Field name made lowercase.
    freguesia = models.CharField(db_column='Freguesia', max_length=255)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'localizacao'

    def __str__(self):
        return self.freguesia


class Proprietario(models.Model):
    nifproprietario = models.CharField(db_column='NIFProprietario', primary_key=True, max_length=11)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255)  # Field name made lowercase.
    telefone = models.IntegerField(db_column='Telefone', blank=True, null=True)  # Field name made lowercase.
    email = models.CharField(db_column='Email', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'proprietario'

    def __str__(self):
        return self.nome


class RedeAgencia(models.Model):
    idrede = models.AutoField(db_column='IDRede', primary_key=True)  # Field name made lowercase.
    densocial = models.CharField(db_column='DenSocial', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'rede_agencia'

    def __str__(self):
        return self.densocial

radarimovel/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import Imovel, Localizacao, Proprietario
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    return render(request, 'radarimovel/index.html')

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
       
        if user is not None:
            login(request, user)
            return redirect('radarimovel:index')  # Redireciona para a página inicial após o login bem-sucedido
        else:
            return render(request, 'radarimovel/login.html', {'error': 'Credenciais inválidas'})
    return render(request, 'radarimovel/login.html')  # Página de login

def user_logout(request):
    logout(request)
    return redirect('radarimovel:index')  # Redirect to the homepage after logout

def imoveis(request):
    imoveis = Imovel.objects.all()

    if request.method == 'POST':
        tipologia = request.POST.get('Tipologia')
        tipoImovel = request.POST.get('tipo_de_imovel')
        endereco = request.POST.get('morada')
        cod_postal = request.POST.get('codigo_postal')
        preco = request.POST.get('preco_pedido')
        area = request.POST.get('area_m2')
        
        preco_max = request.POST.get('preco_max')  # Max price filter
        preco_min = request.POST.get('preco_min')  # Min price filter
        area_max = request.POST.get('area_max')  # Max area filter
        area_min = request.POST.get('area_min') 
        garagem = request.POST.get('garagem_estacionamento')

        filters = {}
        if tipologia:  # Apply filter only if tipologia is provided
            filters['tipologia'] = tipologia
        if tipoImovel:  # Apply filter only if tipoImovel is provided
            filters['tipo_de_imovel'] = tipoImovel
        if endereco:
            filters['morada'] = endereco
        if cod_postal:
            filters['codigo_postal'] = cod_postal
        if preco:
            filters['preco_pedido'] = preco
        if area:
            filters['area_m2'] = area
        if garagem:
            filters['garagem_estacionamento'] = garagem     

        if preco_min:
            filters['preco_pedido__gte'] = preco_min  # Price greater than or equal to min
        if preco_max:
            filters['preco_pedido__lte'] = preco_max  # Price less than or equal to max
        if area_min:
            filters['area_m2__gte'] = area_min  # Area greater than or equal to min
        if area_max:
            filters['area_m2__lte'] = area_max  # Area less than or equal to max 

        if filters:  # Apply the filter only if there's at least one condition
            imoveis = Imovel.objects.filter(**filters)

    return render(request, 'radarimovel/consulta.html', {'imoveis': imoveis})



def inserir(request):

    proprietarios = Proprietario.objects.all()
    localizacao = Localizacao.objects.all()


    if request.method == 'POST':
        nifproprietario = request.POST.get('proprietarios')
        # id_localizacao = request.POST.get('id_localizacao')

        try:
            proprietario_obj = Proprietario.objects.get(nifproprietario=nifproprietario)
            # localizacao_obj = Localizacao.objects.get(id_localizacao=id_localizacao)
        except Proprietario.DoesNotExist:
            print('Proprietario não encontrado')
    

        # idlocalizacao = request.POST['IDLocalizacao']
        tipo_de_imovel = request.POST['Tipo_de_imovel']
        tipologia = request.POST['Tipologia']
        morada = request.POST['Morada']
        codigo_postal = request.POST['Codigo_postal']
        preco_pedido = request.POST['Preco_pedido']
        fotos = None
        area_m2 = request.POST['area_m2']
        garagem_estacionamento = request.POST['garagem_estacionamento']

        novoImovel = Imovel(nifproprietario=proprietario_obj, tipo_de_imovel=tipo_de_imovel, tipologia=tipologia, morada=morada, codigo_postal=codigo_postal, preco_pedido=preco_pedido, fotos=fotos, area_m2=area_m2,garagem_estacionamento=garagem_estacionamento)

        novoImovel.save()

    return render(request, 'radarimovel/inserir.html', {'proprietarios': proprietarios, 'localizacao': localizacao})

radarimovel/templates/radarimovel/consulta.html
{% extends 'radarimovel/layout.html' %} {% block body %}
<div class="consulta_head">
  <h1>Consulta Imóvel</h1>
  <h3>
    Nós ajudamos a encontrar a tua casa de sonho. Não importa o tipo de imóvel,
    tipologia ou área, se consegues sonhar conseguimos encontrar!
  </h3>
</div>

<!-- <label for="imoveis">Escolha um Tipo de Imóvel:</label>

<select name="imoveis" id="imoveis">
  {% for imovel in imoveis %}
  <option value="{{ imovel.nome }}">{{ imovel.tipo_de_imovel }}</option>
  {% endfor %}
</select> -->

<form class="consulta_form" action="" method="POST">
  {% csrf_token %}

  <div class="campo">
    <label class="consulta_label" for="Tipologia">Tipologia</label>
    <input type="text" name="Tipologia" id="Tipologia" />
  </div>
      
  <div class="campo">
    <label class="consulta_label" for="tipo_de_imovel">Tipo</label>
    <input type="text" name="tipo_de_imovel" id="tipo_de_imovel" />
  </div>
      
  <div class="campo">
    <label class="consulta_label" for="morada">Morada</label>
    <input type="text" name="morada" id="morada" />
  </div>
      
  <div class="campo">
    <label class="consulta_label" for="codigo_postal">Código Postal</label>
    <input type="text" name="codigo_postal" id="codigo_postal" />
  </div>
  
  <div class="campo campo_select">
    <label class="consulta_label" for="garagem_estacionamento">Garagem</label>
    <select class="consulta_select" name="garagem_estacionamento" id="garagem_estacionamento">
      <option value="">Garagem?</option>
      <option value="1">Sim</option>
      <option value="0">Não</option>
    </select>
  </div>

  <div class="campo">
    <label class="consulta_label" for="Preço Mínimo">Preço Mínimo</label>
    <input type="text" name="preco_min" id="Preço Mínimo">
  </div>

  <div class="campo">
    <label class="consulta_label" for="Preço Máximo">Preço Máximo</label>
    <input type="text" name="preco_max" id="Preço Máximo">
  </div>
    
  <div class="campo">
    <label class="consulta_label" for="Área Mínima">Área Mínima</label>
    <input type="text" name="area_min" id="Área Mínima">
  </div>

  <div class="campo">
    <label class="consulta_label" for="Área Máxima">Área Máxima</label>
    <input type="text" name="area_max" id="Área Máxima">
  </div>

    
  <button class="btn_consulta" type="submit">Pesquisar</button>
  </form>

  <table class="consulta_table">
    <tr>
      <th>Tipo de Imovél</th>
      <th>Tipologia</th>
      <th>Área</th>
      <th>Morada</th>
      <th>Código Postal</th>
      <th>Preço</th>
    </tr>
    {% for imovel in imoveis %}
    <tr class="tabela_linha">
      <td>{{ imovel.tipo_de_imovel }}</td>
      <td>{{ imovel.tipologia }}</td>
      <td>{{ imovel.area_m2 }} m2</td>
      <td>{{ imovel.morada }}</td>
      <td>{{ imovel.codigo_postal }}</td>
      <td>{{ imovel.preco_pedido }}€</td>
    </tr>
    {% endfor %}
  </table>

  {% endblock %}
</form>

radarimovel/templates/radarimovel/index.html
{% extends "radarimovel/layout.html" %} {% block body %}{% load static %}
<div class="index"></div>
{% endblock %}

radarimovel/templates/radarimovel/inserir.html
{% extends 'radarimovel/layout.html' %} {% block body %}
<div class="consulta_head">
  <h1>Inserir Imóvel:</h1>
  <h3>
    Tens um imóvel que queres vender? Quer sejas particular ou profissional o
    Radar Imóvel é a tua solução.
  </h3>
</div>

<div class="formulario">
  <form class="inserir_form" action="" method="POST">
    {% csrf_token %}
    <div class="label_input">
      <label class="inserir_label" for="proprietarios">Proprietário</label>
      <select name="proprietarios" id="proprietarios" required>
        <option value="">Proprietário?</option>
        {% for proprietario in proprietarios %}
        <option value="{{ proprietario.nifproprietario }}">
          {{ proprietario.nome }}
        </option>
        {% endfor %}
      </select>
    </div>

    <!-- <select name="id_localizacao" id="id_localizacao" required>
      <option value="">-- Selecione uma Freguesia --</option>
      {% for local in localizacao %}
      <option value="{{ local.id_localizacao }}">{{ local.freguesia }}</option>
      {% endfor %}
    </select> -->
    <div class="label_input">
      <label class="inserir_label" for="Tipo_de_imovel">Tipo de Imóvel</label>
      <input type="text" name="Tipo_de_imovel" id="Tipo_de_imovel" />
    </div>

    <div class="label_input">
      <label class="inserir_label" for="Tipologia">Tipologia</label>
      <input type="text" name="Tipologia" id="Tipologia" />
    </div>

    <div class="label_input">
      <label class="inserir_label" for="Morada">Morada</label>
      <input type="text" name="Morada" id="Morada" />
    </div>

    <div class="label_input">
      <label class="inserir_label" for="Codigo_postal">Código Postal</label>
      <input type="text" name="Codigo_postal" id="Codigo_postal" />
    </div>

    <div class="label_input">
      <label class="inserir_label" for="Preco_pedido">Preço</label>
      <input type="text" name="Preco_pedido" id="Preco_pedido" />
    </div>

    <div class="label_input">
      <label class="inserir_label" for="Fotos">Fotos</label>
      <input type="file" name="Fotos" id="Fotos" />
    </div>

    <div class="label_input">
      <label class="inserir_label" for="area_m2">Área</label>
      <input type="text" name="area_m2" id="area_m2" />
    </div>

    <div class="label_input">
      <label class="inserir_label" for="garagem_estacionamento">Garagem</label>

      <select name="garagem_estacionamento">
        <option value="1">Sim</option>
        <option value="0">Não</option>
      </select>

      <!-- <input
          type="text"
          name="garagem_estacionamento"
          id="garagem_estacionamento"
        /> -->
    </div>
    <button class="btn_inserir" type="submit">Adicionar</button>
  </form>
</div>

{% endblock %}

radarimovel/templates/radarimovel/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Coiny&family=Nunito:ital,wght@0,200..1000;1,200..1000&family=Red+Rose:wght@300..700&family=Sono:wght@200..800&display=swap"
      rel="stylesheet"
    />
    <link href="{% static 'radarimovel/styles.css' %}" rel="stylesheet" />
    <script defer src="{% static 'radarimovel/script.js' %}"></script>
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'radarimovel/favicon.ico' %}"
    />
    <title>Radar Imóvel</title>
  </head>
  <body>
    <header class="header">
      <a href="{% url 'radarimovel:index' %}">
        <img
          src="{% static 'radarimovel/logo.png' %}"
          alt="Radar Imóvel"
          class="logo"
        />
      </a>
      <nav>
        <ul class="nav">
          <li>
            <a href="{% url 'radarimovel:consulta' %}">Consultar Imóveis</a>
          </li>
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'radarimovel:inserir' %}">Inserir Imóvel</a>
          </li>
          <li>
            <a href="{% url 'radarimovel:logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'radarimovel:login' %}">Login</a>
            {% endif %}
          </li>
        </ul>
      </nav>
    </header>

    {% block body %} {% endblock %}
    <footer class="footer">&copy; <span id="year"></span> Radar Imovél</footer>
  </body>
</html>

radarimovel/templates/radarimovel/login.html
{% extends 'radarimovel/layout.html' %} {% block body %}

<div class="container_login">
  <h1>Inicia sessão ou regista-te</h1>
  <form class="login_form" method="POST">
    {% csrf_token %}
    <label class="login_label" for="username">Nome de Utilizador</label>
    <input
      class="login_input"
      type="text"
      name="username"
      id="username"
      required
    />
    <label class="login_label" for="password">Palavra-passe</label>
    <input
      class="login_input"
      type="password"
      name="password"
      id="password"
      required
    />
    <button class="btn_login" type="submit">Entrar</button>
  </form>
</div>
<!-- <button type="submit">Particular</button>
<button type="submit">Profissional</button> -->
{% endblock %}